import { prisma } from "@/lib/prisma";

export const buildUserDataExport = async (user: { id: string }) =>
  prisma.$transaction(async (tx) => {
    const [
      userProfile,
      preferences,
      moodEntries,
      medications,
      therapySessions,
      exercises,
      caregiverRelationships,
      caregiverObservations,
      caregiverEvents,
      caregiverAccessLog,
    ] = await Promise.all([
      tx.user.findUnique({
        where: { id: user.id },
        select: {
          id: true,
          email: true,
          name: true,
          image: true,
          emailVerified: true,
          createdAt: true,
          updatedAt: true,
        },
      }),
      tx.userPreferences.findUnique({
        where: { userId: user.id },
        select: {
          hasCompletedOnboarding: true,
          onboardingStep: true,
          defaultChartPeriod: true,
          timezone: true,
          theme: true,
          notificationsEnabled: true,
          dailyCheckInReminder: true,
          dailyCheckInTime: true,
          medicationReminders: true,
          medicationReminderTime: true,
          createdAt: true,
          updatedAt: true,
        },
      }),
      tx.moodEntry.findMany({
        where: { userId: user.id },
        orderBy: { createdAt: "asc" },
        select: {
          id: true,
          value: true,
          note: true,
          energy: true,
          sleepHours: true,
          sleepQuality: true,
          sleepDisturbances: true,
          anxiety: true,
          tags: true,
          sideEffects: true,
          createdAt: true,
          updatedAt: true,
        },
      }),
      tx.medication.findMany({
        where: { userId: user.id },
        orderBy: { createdAt: "asc" },
        select: {
          id: true,
          name: true,
          dosage: true,
          frequency: true,
          isPRN: true,
          isArchived: true,
          scheduleTimes: true,
          weeklyDay: true,
          createdAt: true,
          updatedAt: true,
          intakes: {
            orderBy: { takenAt: "asc" },
            select: {
              id: true,
              takenAt: true,
              skipped: true,
              note: true,
              scheduledForDate: true,
              doseIndex: true,
              createdAt: true,
            },
          },
          history: {
            orderBy: { changedAt: "asc" },
            select: {
              id: true,
              dosage: true,
              previousDosage: true,
              reason: true,
              changedAt: true,
            },
          },
        },
      }),
      tx.therapySession.findMany({
        where: { userId: user.id },
        orderBy: { date: "asc" },
        select: {
          id: true,
          date: true,
          notes: true,
          benefitRating: true,
          createdAt: true,
          updatedAt: true,
        },
      }),
      tx.exercise.findMany({
        where: { userId: user.id },
        orderBy: { createdAt: "asc" },
        select: {
          id: true,
          name: true,
          description: true,
          isArchived: true,
          createdAt: true,
          updatedAt: true,
          logs: {
            orderBy: { completedAt: "asc" },
            select: {
              id: true,
              completedAt: true,
              note: true,
              createdAt: true,
            },
          },
        },
      }),
      tx.caregiverRelationship.findMany({
        where: {
          OR: [{ patientId: user.id }, { caregiverId: user.id }],
        },
        orderBy: { createdAt: "asc" },
        select: {
          id: true,
          patientId: true,
          caregiverId: true,
          caregiverEmail: true,
          role: true,
          label: true,
          permissions: true,
          status: true,
          inviteExpiry: true,
          createdAt: true,
          updatedAt: true,
        },
      }),
      tx.caregiverObservation.findMany({
        where: {
          OR: [{ observerId: user.id }, { subjectId: user.id }],
        },
        orderBy: { createdAt: "asc" },
        select: {
          id: true,
          observerId: true,
          subjectId: true,
          moodObserved: true,
          energyObserved: true,
          socialBehavior: true,
          sleepObserved: true,
          notes: true,
          visibleToPatient: true,
          createdAt: true,
          updatedAt: true,
        },
      }),
      tx.caregiverEvent.findMany({
        where: {
          OR: [{ reporterId: user.id }, { subjectId: user.id }],
        },
        orderBy: { eventDate: "asc" },
        select: {
          id: true,
          reporterId: true,
          subjectId: true,
          eventType: true,
          severity: true,
          description: true,
          eventDate: true,
          visibleToPatient: true,
          createdAt: true,
          updatedAt: true,
        },
      }),
      tx.caregiverAccessLog.findMany({
        where: {
          OR: [{ patientId: user.id }, { caregiverId: user.id }],
        },
        orderBy: { accessedAt: "asc" },
        select: {
          id: true,
          patientId: true,
          caregiverId: true,
          relationshipId: true,
          resource: true,
          accessedAt: true,
        },
      }),
    ]);

    return {
      exportMetadata: {
        exportDate: new Date().toISOString(),
        dataVersion: "2.1",
        applicationName: "Moodday",
        userId: user.id,
        timezone: preferences?.timezone ?? null,
        excludedSecurityData: [
          "authentication sessions and credentials",
          "push subscription secrets",
          "Stripe identifiers",
          "caregiver invitation tokens",
          "offline operation identifiers",
        ],
      },
      user: userProfile,
      preferences,
      moodEntries,
      medications,
      therapySessions,
      exercises,
      caregiverCircle: {
        relationships: caregiverRelationships,
        observations: caregiverObservations,
        events: caregiverEvents,
        accessLog: caregiverAccessLog,
      },
    };
  });
